### ISSUE TITLE
About equation

### ISSUE THREAD

**Issue by XinyueZhangHust** [btjhjeon/IMM_tensorflow#1]
Hello, I read your excellent paper, but due to my lack of mathematical foundation, I encountered some problems in formula reasoning. Can you deduce in detail how Equation 3 to Equation 8 is implemented as a whole, and if so, thank you very much for your help.

**Comment by XinyueZhangHust** [comment]
What is the connection between the derivation of the equations in Section 3 and the Weight Transfer, L2 Transfer, and Dropout Transfer?

**Comment by btjhjeon** [comment]
Sorry for late response.

The mean-IMM is a method that approximates a Gaussian mixture as a single Gaussian through alpha blending, in the equation 3-5. And the mode-IMM uses Laplacian approximation to approximate Gaussian mixture. In the process, Fisher information is used as a mode. (c.f. equation 6-8)

Weight Transfer, L2 Transfer, and Dropout Transfer are different methods for multi-task transfer learning.

**Comment by XinyueZhangHust** [comment]
Thank you for your assistance and for answering my questions.
