### ISSUE TITLE
about L2 transfer

### ISSUE THREAD

**Issue by Piao-Hu** [btjhjeon/IMM_tensorflow#2]
Hello, In the paper, you said that"L2-transfer is a variant of L2-regularization.", and in the code, the default lamda for is -1, so I am wondering if the difference between L2-transfer and L2-regularization is about the sign, or L2-transfer is equal to the L2-regularization?
I would be grateful if you could help me.

**Comment by btjhjeon** [comment]
“L2-transfer is a variant of L2-regularization.”
The intention was that we proposed L2-transfer using the L2-regularization concept. L2-regularization has a penalty term which prevent diverging the weight from 0. Similarly, L2-transfer has a penalty term which prevent deviating the weight significantly from the value of the previous weight in the equation 10.

In the tensorflow 1 version, the method of indicating mandatory arguments required one more line of code. So you need to enter the arguments of which the value is "-1" as default.
